environment:
  version_suffix: alpha
  
version: 1.0.0-$(version_suffix){build}

# branches to build
branches:
  # blacklist
  except:
  - master

image: Visual Studio 2017
configuration: Release
# Patch .NET Core/Standard *.csproj files for versioning:
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'


# restore Nuget packages before build:
before_build:
- nuget restore

build:
  publish_nuget: true
  verbosity: minimal

artifacts:
  #- path: CQRSlight\bin\$(configuration)\**\*.nupkg
  - path: '**\*.nupkg'
  
  - path: CQRSlight\*.csproj

#deploy:
# - provider: NuGet
#   server: https://ci.appveyor.com/nuget/cqrslight-v185sxsmoqs3
#   api_key:
#    secure: bfsoe95844c15naapbmlwayo
#   skip_symbols: false
#   symbol_server: https://your.symbol.server/feed
#   artifact: MyPackage.nupkg

# # Deploy to GitHub Releases
# - provider: GitHub
#   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
#   draft: false
#   prerelease: false
#   on:
#     branch: master                # release from master branch only
#     appveyor_repo_tag: true       # deploy on tag push only 
  
# send notification to Slack about build results
notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: builds
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true