version: 1.0.{build}

environment:
  version_suffix: alpha

branches:
  except:
  - master

image: Visual Studio 2017
configuration: Release
# Patch .NET Core/Standard *.csproj files for versioning:
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}$(version_suffix)$(appveyor_build_version)'
  package_version: '{version}$(version_suffix)$(appveyor_build_version)'
  assembly_version: '{version}$(version_suffix)$(appveyor_build_version)'
  file_version: '{version}$(version_suffix)$(appveyor_build_version)'
  informational_version: '{version}$(version_suffix)$(appveyor_build_version)'


# restore Nuget packages before build:
before_build:
- nuget restore

build:
  publish_nuget: true
  verbosity: minimal
  
# send notification to Slack about build results
notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: builds
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true